#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
done
TOOL_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
source "${TOOL_DIR}/core/engine.sh"
main "$@"
